language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - RUN_TESTS=1 # dev
  - RUN_TESTS=1 COMPOSER_EXTRA_ARGS="--prefer-stable"
  - RUN_TESTS=1 COMPOSER_EXTRA_ARGS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" COVERAGE="1"
  exclude:
    - php: 7.4
      env: COMPOSER_EXTRA_ARGS="--prefer-stable"
  allow_failures:
    - env: RUN_TESTS=1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist $COMPOSER_EXTRA_ARGS # update because we may need --prefer-lowest option

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - if [ "$COVERAGE" != "" ]; then php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
